{
  data_dir: '../data/bms',
  context_name: 'prod1',
  model_name: 'v1_lr0',
  dataset_sample_size: 1000,
  #learning_rate: 1.e-4,
  num_epochs: 30,
  train_batch_size: 512,
  eval_batch_size: 1280,
  #save_per_batch_iter: 100,
  
  # restore_model_path: '../data/bms/prod1/v1_20210502_192148/model_final_20210430_091724.pth',
  eval_model_names: ['v1_lr0_20210503_183111',
                     'v1_lr1_20210503_185221',
                     'v1_lr2_20210503_190953',
                     'v1_lr3_20210503_192721',
                     'v1_lr4_20210503_194451'],
  eval_dataset_types: ['val']
}

