{
  data_dir: '../data/bms',
  context_name: 'prod1',
  model_name: 'v1r1',
  num_epochs: 20,
  train_batch_size: 512,
  eval_batch_size: 1280,
  learning_rate: 1.e-2,
  dataset_sample_size: 1000,

  # restore_model_path: '../data/bms/prod1/v1_20210502_192148/model_final_20210430_091724.pth',
  eval_model_names: ['v1_20210502_192148'],
  eval_dataset_types: ['val', 'train']
}
